### ISSUE TITLE
frp_connect network error: not manually attachable

### ISSUE THREAD

**Issue by vishiswoz** [frankli0324/ctfd-whale#9]
Hi I'm trying to use this plugin with a personal CTFd instance, and I'm running into this issues whenever I try to run  `docker-compose up -d`:

```
Error response from daemon: Could not attach to network ctfd_frp_connect: rpc error: code = PermissionDenied desc = network ctfd_frp_connect not manually attachable
```

This happens when trying to start the `ctfd-frps-1` container, or the `frps` service. I was following the installation guide here: https://github.com/frankli0324/ctfd-whale/blob/master/docs/install.md.

Relevant part of my `docker-compose.yml` file:

```yml
  frps:
    image: glzjin/frp
    restart: always
    volumes:
      - ./conf/frp:/conf
    entrypoint:
      - /usr/local/bin/frps
      - -c
      - /conf/frps.ini
    ports:
      - 10000-10500:10000-10500
      - 8001:8001
    networks:
      default:
      frp_connect:
  frpc:
    image: glzjin/frp:latest
    restart: always
    volumes:
      - ./conf/frp:/conf/
    entrypoint:
      - /usr/local/bin/frpc
      - -c
      - /conf/frpc.ini
    depends_on:
      - frps
    networks:
        frp_containers:
        frp_connect:
            ipv4_address: 172.1.0.4

networks:
    default:
    internal:
        internal: true
    frp_connect:
        driver: overlay
        internal: true
        ipam:
            config:
                - subnet: 172.1.0.0/16
    frp_containers:
        driver: overlay
        internal: true
        attachable: true
        ipam:
            config:
                - subnet: 172.2.0.0/16
```

I read online that I maybe have to set put `attachable: true` for the `frp_connect` network? Please let me know if that's the case.
